        //             "首页"
        export const indexPath = "/pages/index/index"
        //             "食堂管理"
        export const indexCanteenPath = "/pages/index/canteen-manager/index"
        //             "学习考核"
        export const indexStudyPath = "/pages/index/study-check/index"
        //             "任务"
        export const indexTaskPath = "/pages/index/task/index"
        //             "登录"
        export const loginPath = "/pages/login/index"
        //             "工作台"
        export const platformPath = "/pages/platform/index"
        //             "食堂管理"
        export const platformCanteenPath = "/pages/platform/canteen-manager/index"
        //             "食安信息"
        export const platformBaseInfoPath = "/pages/platform/base-info/index"
        //             "食安员自查"
        export const platformCheckSelfPath = "/pages/platform/check-self/index"
        //             "点评评论"
        export const platformCommentPath = "/pages/platform/comment/index"
        //             "添加评论"

        export const platformCommentAddPath = "/pages/platform/comment-add/index"
        //             "陪餐公示"
        export const platformCompanyPath = "/pages/platform/company/index"
        //             "培训记录"
        export const platformTrainPath = "/pages/platform/train/index"
        //             "创建培训"
        export const platformTrainAddPath = "/pages/platform/train-add/index"
        //             "用餐人数"
        export const platformMealCountPath = "/pages/platform/meal-count/index"
        //             "新增用餐"
        export const platformMealCountAddPath = "/pages/platform/meal-count-add/index"
        //             "安全知识"
        export const platformSecurityPath = "/pages/platform/security-knowledge/index"
        //             "安全知识详情"
        export const platformSecurityDetailPath = "/pages/platform/security-knowledge-detail/index"
        
        //             "留样管理"
        export const platformSamplePath = "/pages/platform/sample/index"
        //             "留样添加"
        export const platformSampleAddPath = "/pages/platform/sample-add/index"
        //             "留样详情"
        export const platformSampleDetailPath = "/pages/platform/sample-detail/index"

        //             "采购验收"
        export const platformPurchasePath = "/pages/platform/purchase/index"
        //             "采购验收添加"
        export const platformPurchaseAddPath = "/pages/platform/purchase-add/index"
        //             "采购验收详情"
        export const platformPurchaseDetailPath = "/pages/platform/purchase-detail/index"
        //             "废弃物"
        export const platformGarbagePath = "/pages/platform/garbage/index"
        //             "废弃物添加"
        export const platformGarbageAddPath = "/pages/platform/garbage-add/index"
        //             "废弃物详情"
        export const platformGarbageDetailPath = "/pages/platform/garbage-detail/index"
        //             "清洗"
        export const platformWashPath = "/pages/platform/wash/index"
        //             "清洗添加"
        export const platformWashAddPath = "/pages/platform/wash-add/index"
        //             "清洗详情"
        export const platformWashDetailPath = "/pages/platform/wash-detail/index"
        //             "添加剂"
        export const platformAdditivePath = "/pages/platform/additive/index"
        //             "添加剂添加"
        export const platformAdditiveAddPath = "/pages/platform/additive-add/index"
        //             "添加剂详情"
        export const platformAdditiveDetailPath = "/pages/platform/additive-detail/index"
        //             "消毒台账"
        export const platformDisinfectantPath = "/pages/platform/disinfectant/index"
        //             "消毒台账添加"
        export const platformDisinfectantAddPath = "/pages/platform/disinfectant-add/index"
        //             "消毒台账详情"
        export const platformDisinfectantDetailPath = "/pages/platform/disinfectant-detail/index"
        //             "健康证管理"
        export const platformHealthPath = "/pages/platform/health-certification/index"
        //             "直播"
        export const platformLivePath = "/pages/platform/live/index"
        //             "菜单公示"
        export const platformMenuPath = "/pages/platform/menu/index"
        //             "菜单添加"
        export const platformMenuAddPath = "/pages/platform/menu-add/index"
        //             "晨检记录"
        export const platformMorningCheckPath = "/pages/platform/morning-check/index"
        //             "添加晨检"
        export const platformMorningCheckAddPath = "/pages/platform/morning-check-add/index"
        //             "晨检记录详情"
        export const platformMorningCheckDetailPath = "/pages/platform/morning-check-detail/index"

        //             "任务"
        export const platformTaskPath = "/pages/platform/task/index"
        //             "任务"
        export const taskPath = "/pages/task/index"
        //             "创建任务"
        export const taskCreatePath = "/pages/task/create-task/index"
        //             "任务详情"
        export const taskDetailPath = "/pages/task/task-detail/index"
        //             "我的"
        export const minePath = "/pages/mine/index"